name: Keep Supabase Alive

on:
  schedule:
    # Run every 6 days at 2 AM UTC
    - cron: '0 2 */6 * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Supabase Active
        run: |
          response=$(curl -s -w "\n%{http_code}" https://aiflows.pro/api/keep-alive)
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n-1)
          
          echo "Response: $body"
          echo "HTTP Code: $http_code"
          
          if [ "$http_code" != "200" ]; then
            echo "Failed to keep Supabase alive"
            exit 1
          fi
          
      - name: Log Success
        if: success()
        run: echo "✅ Supabase kept alive successfully at $(date)"